### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by asewnath** [JCSDA-internal/evagram#12]
We will be developing a presentation to share evagram progress with other members of the GMAO. Tariq had a great list in the meeting chat that we can work off of.

Akira:

- [x]  Slides to introduce the idea of evagram (answering "why evagram?")

Brandon:

- [x] Discuss Django and why it is a powerful backend tool for web development. If there's anything to highlight about the Django implementation add that here.
- [x] Talk about React and why it was your choice for frontend development. If there's anything to highlight about the React part of the implementation add that here.
- [x] Discuss schema we developed and why postgreSQL was chosen (@tariqhamzeyssai the choice is because discover has support for postgreSQL right?)
- [x] Discuss input tool and github action work, talk about the need for testing at each PR for continuous integration
- [x] Switch over to a live demo and demonstrate the functionality
- [x] Slide on future work (we will help with this one too)

**Comment by ghost** [comment]
@asewnath RE Why Postgresql:  Yes that's correct.  We have 2 web apps (Scorecard and QuADS) that use the postgresql database hosted on edb1.

**Comment by asewnath** [comment]
Oh cool I didn't know the scorecard was also using postgresql

**Comment by asewnath** [comment]
@brandonzhu09 Good job putting together the final presentation!
