### ISSUE TITLE
Generalize Input Tool

### ISSUE THREAD

**Issue by asewnath** [JCSDA-internal/evagram#17]
## Description
Input tool needs to be a standalone module that can be called by both a swell task and evagram database testing. Input tool will take in a dictionary, process the dictionary, and then proceed to add to the database.

** Note that the input tool itself will not be responsible for database connections. These connections are established before input_tool is called and psycopg2 objects like "cur" can be passed to the input tool.

In terms of the database connection in evagram, you can modify it to reflect what is found in a .pgpass file. This file contains one line: `hostname:port:database:username:password`. Setting up the database connection in swell is outside the scope of this issue.

Dictionary that swell provides will look like this:
```
evagram_dict = { 
     'owner': 'bzhu',
     'experiment': 'experiment1',
     'eva_directory': '/path/to/eva/plots'
} 
```
Steps to complete:
- [x] @asewnath Make evagram_input repository in GEOS-ESM
- [x] In the separate repository, modify the input tool to take in a dictionary and database connection, add code to process dictionary fields, remove any hardcoding the tool doesn't need, etc.
- [x] In evagram, change "input_tool" to "database_manager" and call input tool there as a module. Verify these changes are working locally
- [x] Create Initial PR in evagram_input
- [x] Add python coding norms test/github action to evagram_input
- [x] Merge evagram_input PR into develop
- [x] Create PR in evagram for changes associated with evagram_input
- [x] Merge evagram PR
- [x] Create evagram_input github action calling evagram for database test

## Acceptance Criteria (Definition of Done)
Input tool is a standalone python module. Input tool is successfully imported and executed during evagram database testing

**Comment by asewnath** [comment]
@brandonzhu09 We've created a new evagram_input repository here: https://github.com/GEOS-ESM/evagram_input. I think you need to accept an invitation to GEOS-ESM in order to access it

**Comment by brandonzhu09** [comment]
I have received the invitation and I can see the new repository. Do you still need me to create my own private repository or is it ok that I work on the `evagram_input` repo in GEOS?

**Comment by asewnath** [comment]
> I have received the invitation and I can see the new repository. Do you still need me to create my own private repository or is it ok that I work on the `evagram_input` repo in GEOS?

No need to create your own private repo. Make a branch on evagram_input and add your code there

**Comment by brandonzhu09** [comment]
Sounds good, thanks!

**Comment by asewnath** [comment]
- [ ] Add session code into input tool (experiment with class structure)
- [ ] get evagram_input package installable (`setup.py`, `__init__.py`)
- [ ] make evagram_input test using previous evagram database test
- [ ] Make PR for evagram_input
- [ ] Rewrite evagram database test to use Django models

@tariqhamzeyssai Let me know if I forgot anything

**Comment by ghost** [comment]
>"using previous evagram database test"

Yes, So, for now just use the existing database running on your local.  For the future, I'm wondering if evagram_input CI can automatically harvest the up-to-date .sql files in evagram without making the entire evagram package a dependency.  That, or somehow sync the .sql files between each repository.

**Comment by tariqhamzeyssai** [comment]
@brandonzhu09 Do you use this?  https://django-test-utils.readthedocs.io/en/latest/testmaker.html

**Comment by ghost** [comment]
evagram tests should focus on views more than the schema https://docs.djangoproject.com/en/5.0/topics/testing/tools/
