### ISSUE TITLE
Bokeh :(

### ISSUE THREAD

**Issue by asewnath** [JCSDA-internal/evagram#24]
## Description

Different Bokeh versions between eva and evagram can result in catastrophic incompatibilities. A strategy for maintaining the same bokeh version as eva needs to be developed.

**Comment by asewnath** [comment]
Versions seem to be backward compatible. Use latest version and add bokeh-widgets, bokeh-tables, and bokeh-api scripts to index.html

**Comment by brandonzhu09** [comment]
Should I close this issue as resolved? The fix Akira mentioned fixed the problem for me.

**Comment by asewnath** [comment]
@brandonzhu09 yeah you can resolve it
